# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\data0\HOC_DAI_HOC_VKU\NAM3_HK1\Network Programing\Projects\do_an_mon_hoc\AloApp\alo_app\ui\log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 361)
        self.loginWidget = QtWidgets.QWidget(Form)
        self.loginWidget.setGeometry(QtCore.QRect(0, 0, 371, 361))
        self.loginWidget.setStyleSheet("background-color: rgba(250,250,250,100)")
        self.loginWidget.setObjectName("loginWidget")
        self.loginTitle = QtWidgets.QLabel(self.loginWidget)
        self.loginTitle.setGeometry(QtCore.QRect(0, 30, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setStrikeOut(False)
        self.loginTitle.setFont(font)
        self.loginTitle.setStyleSheet("color: rgb(0, 150, 150)")
        self.loginTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.loginTitle.setObjectName("loginTitle")
        self.inputLoginUsername = QtWidgets.QLineEdit(self.loginWidget)
        self.inputLoginUsername.setGeometry(QtCore.QRect(50, 110, 271, 31))
        self.inputLoginUsername.setStyleSheet("border: 1px solid rgb(0, 150, 150); border-radius: 15px; padding: 7px; ")
        self.inputLoginUsername.setText("")
        self.inputLoginUsername.setObjectName("inputLoginUsername")
        self.usernameLabel = QtWidgets.QLabel(self.loginWidget)
        self.usernameLabel.setGeometry(QtCore.QRect(50, 90, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("color: rgb(0, 150, 150)")
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.loginWidget)
        self.passwordLabel.setGeometry(QtCore.QRect(50, 150, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("color: rgb(0, 150, 150)")
        self.passwordLabel.setObjectName("passwordLabel")
        self.inputLoginPassword = QtWidgets.QLineEdit(self.loginWidget)
        self.inputLoginPassword.setGeometry(QtCore.QRect(50, 170, 271, 31))
        self.inputLoginPassword.setStyleSheet("border: 1px solid rgb(0, 150, 150); border-radius: 15px; padding: 7px; ")
        self.inputLoginPassword.setText("")
        self.inputLoginPassword.setObjectName("inputLoginPassword")
        self.btnLogin = QtWidgets.QPushButton(self.loginWidget)
        self.btnLogin.setGeometry(QtCore.QRect(140, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("border-radius: 15px; backgrouNd-color: rgb(0, 150, 150); color: white;")
        self.btnLogin.setObjectName("btnLogin")
        self.label = QtWidgets.QLabel(self.loginWidget)
        self.label.setGeometry(QtCore.QRect(50, 260, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("padding: 0px ")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loginTitle.setText(_translate("Form", "LOGIN"))
        self.usernameLabel.setText(_translate("Form", "Username:"))
        self.passwordLabel.setText(_translate("Form", "Password:"))
        self.btnLogin.setText(_translate("Form", "LOGIN"))
        self.label.setText(_translate("Form", "TextLabel"))
